version: "3.8"
services:
  bikeshop-nginx:
    container_name: bikeshop-nginx
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./docker/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - bikeshop-backend
    networks:
      - app-network
  bikeshop-backend:
    container_name: bikeshop-backend
    image: node:18.15-alpine
    restart: unless-stopped
    build:
      context: .
    links:
      - bikeshop-mongo
    networks:
      - app-network
  bikeshop-mongo:
    container_name: bikeshop-mongo
    restart: unless-stopped
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    volumes:
      - mongodb:/data/db
      - ./docker/mongo:/etc/mongo/
    networks:
      - app-network
    ports:
      - '27017:27017'
  #certbot:
  #  image: certbot/certbot:nightly
  #  container_name: certbot
  #  volumes:
  #    - certbot-etc:/etc/letsencrypt
  #    - certbot-var:/var/lib/letsencrypt
  #    - web-root:/var/www/html
  #  depends_on:
  #    - bikeshop-nginx
  #  command: certonly --webroot --webroot-path=/var/www/html --email williambeukelman@my.cwi.edu --agree-tos --no-eff-email --force-renewal -d thebikeshop.app

volumes:
  certbot-etc:
  certbot-var:
  mongodb:
    driver: local
    driver_opts:
      type: none
      device: ./docker/data
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./docker/web-root
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./docker/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
