version: "3"
services:
  bikeshop-nginx:
    container_name: bikeshop-nginx
    image: nginx
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:80"
      - "10443:443"
    volumes:
      - web-root:/var/www/html
      - ./docker/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - bikeshop-backend
    networks:
      - app-network
  bikeshop-backend:
    container_name: bikeshop-backend
    image: node:18.15-alpine
    restart: unless-stopped
    build:
      context: .
    #ports:
    #  - "8081:8081"
    links:
      - bikeshop-mongo
    networks:
      - app-network
  bikeshop-mongo:
    container_name: bikeshop-mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - ./docker/data:/data/db
    networks:
      - app-network
    #ports:
    #  - '27018:27017'
  certbot:
    image: certbot/certbot:nightly
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - bikeshop-nginx
    command: certonly --webroot --webroot-path=/var/www/html --email williambeukelman@my.cwi.edu --agree-tos --no-eff-email --force-renewal -d thebikeshop.app

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./docker/web-root
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: .docker/dhparam/
      o: bind

networks:
  app-network:
    #external: true
    driver: bridge
